name: "Test & Lint"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -fsSL -o ./shfmt https://github.com/mvdan/sh/releases/download/v3.1.2/shfmt_v3.1.2_linux_amd64
          chmod 700 ./shfmt
      - run: ./shfmt -i 4 -l -d dracut-efi
      - run: shellcheck -S style -o all dracut-efi
